import { FetchXMLRowStructure } from "./CloudScapeTableConfig";

export const SAMPLE_DATA: FetchXMLRowStructure[] = [
  {
    fullname: "1",
    companyname: "App 1",
    cb_athenabusinesslegalname: "app1",
    address1_composite: "General",
    createdon: "2023-08-12",
    modifiedon: "2023-08-2",
    cb_lastactivitydate: "2023-08-12",
    cb_programleadsource: "Data Import",
    statuscode: "New",
  },
  {
    fullname: "2",
    companyname: "App 2",
    cb_athenabusinesslegalname: "app2",
    address1_composite: "Features",
    createdon: "2023-08-20",
    modifiedon: "2023-08-19",
    cb_lastactivitydate: "2023-08-19 15:30:00",
    cb_programleadsource: "Web Lead",
    statuscode: "Active",
  },
  {
    fullname: "3",
    companyname: "App 3",
    cb_athenabusinesslegalname: "app3",
    address1_composite: "General3",
    createdon: "2023-08-20",
    modifiedon: "2023-08-20",
    cb_lastactivitydate: "2023-08-19",
    cb_programleadsource: "Rep enter",
    statuscode: "New",
  },
  {
    fullname: "Page Rick",
    companyname: "Apple Inc ltm",
    cb_athenabusinesslegalname: "app1",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2023-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Bizlead",
    statuscode: "Active",
  },
  {
    fullname: "Page Rick",
    companyname: "Apple Inc ltm",
    cb_athenabusinesslegalname: "app1",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2023-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Bizlead",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },

  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
  {
    fullname: "Rick page",
    companyname: "Apple Inc",
    cb_athenabusinesslegalname: "application 145",
    address1_composite: "General",
    createdon: "2020-08-20",
    modifiedon: "2020-08-20",
    cb_lastactivitydate: "2023-08-20",
    cb_programleadsource: "Athena",
    statuscode: "Active",
  },
];
